# Generated by Django 5.2.6 on 2026-05-23 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisECG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(blank=True, max_length=100)),
                ('modo', models.CharField(choices=[('demo', 'Demo'), ('anotado', 'Con Anotaciones'), ('produccion', 'Producción')], default='demo', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_latidos', models.IntegerField(default=0)),
                ('latidos_procesados', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('modelo_version', models.CharField(default='ultra_best.keras', max_length=100)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analisis_ecg', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis ECG',
                'verbose_name_plural': 'Análisis ECG',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
