# Generated by Django 5.2.6 on 2026-05-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_analisisecg_cloudinary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analisisecg',
            new_name='classifier__usuario_ddcb23_idx',
            old_name='analisis_usuario_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='analisisecg',
            new_name='classifier__pacient_e2ca07_idx',
            old_name='analisis_paciente_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='analisisecg',
            new_name='classifier__modo_8531cf_idx',
            old_name='analisis_modo_usuario_idx',
        ),
    ]
