# Generated by Django 5.2.6 on 2026-05-29 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_rename_analisis_usuario_fecha_idx_classifier__usuario_ddcb23_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario_cuenta',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario del paciente en el sistema (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
