# Generated by Django 5.2.6 on 2026-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_uuid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería'), ('PAS', 'Pasaporte'), ('RUC', 'RUC'), ('OTR', 'Otro')], default='DNI', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institucion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_colegiatura',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orcid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carné de Extranjería'), ('PAS', 'Pasaporte'), ('RUC', 'RUC'), ('OTR', 'Otro')], default='DNI', max_length=10),
        ),
    ]
